version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    # Não há dependência de contêiner postgres local
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - NODE_ENV=production
      - SESSION_SECRET=${SESSION_SECRET}
    restart: always

  # Não usamos um contêiner de banco de dados local
  # O armazenamento é feito no Supabase